name: Create artifact
on: [push]

env:
  ARTIFACT_NAME: myartifact
  
jobs:
  main:
    name: Main job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: .
